server:
  port: 8000
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pokuyo/config-repository

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true